name = "bemusterungstool"
main = "worker.js"
compatibility_date = "2025-01-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "bemusterungstool"
database_id = "696ecc2e-d9a5-4be6-9f3f-646c8928243f" # Wird nach Erstellung eingetragen


[assets]
directory = "public"

# Umgebungsvariablen (optional)
[vars]
ENVIRONMENT = "production"
